# Generated by Django 4.2.5 on 2023-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=100)),
                ('last_name', models.CharField(help_text='Last Name', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='(not required but needed if you expect a answer)', max_length=100, verbose_name='Your E-Mail Address')),
                ('options', models.CharField(choices=[('security', 'Security'), ('problem', 'Problem'), ('questions', 'Questions'), ('praise/criticism', 'Praise/Criticism'), ('other', 'Other')], default='questions', max_length=100)),
                ('message', models.TextField(help_text='Please describe your matter.', max_length=1400)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.FileField(upload_to='media')),
            ],
        ),
    ]
