# Generated by Django 4.2.5 on 2023-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMZProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('total_rating', models.IntegerField(default=0)),
                ('description', models.TextField(error_messages={'required': 'Description is required.'}, max_length=2000)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
