# Generated by Django 4.2.5 on 2023-10-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_amzproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='amzproduct',
            name='category',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
